[settings]
idiomatic_version_file_enable_tools = ["python"]

[tools]
uv = "latest"
pipx = "latest"
starship = "latest"
zoxide = "latest"
fzf = "latest"
tlrc = "latest"
usage = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
bat-extras = "latest"
"pipx:detect-secrets" = "latest"
pre-commit = "latest"
